//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever.Core.HUD;
    
    
    public class GameMainMessenger : NeverSayNever.Core.HUD.UIPanelMessenger
    {
        
        public GameMainMessenger(string name) : 
                base(name)
        {
        }
    }
}
