//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever;
    
    public partial class GameMainPanel : NeverSayNever.UIBasePanel
    {
        private TextMeshProUGUI tmp_title;
        private Button btn_start;
        private Button btn_option;
        private Button btn_quit;
        
        protected override void OnInitAttribute()
        {
            base.OnInitAttribute();
            this.tmp_title = Info.Collection["tmp_title"] as TMPro.TextMeshProUGUI;
            this.btn_start = Info.Collection["btn_start"] as UnityEngine.UI.Button;
            this.btn_option = Info.Collection["btn_option"] as UnityEngine.UI.Button;
            this.btn_quit = Info.Collection["btn_quit"] as UnityEngine.UI.Button;
        }
    }
}
