//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever;

    public partial class GameMainPanel : NeverSayNever.UIBasePanel
    {
        
        protected override void OnAwake()
        {
            base.OnAwake();

            btn_start.AddClickListener(()=>{
                NsnLog.Print("���� ----- �����ʼ��ť");

                SceneMgr.LoadSceneAsync("example_scene");
                //UIMgr.Instance.ClosePanel(UIModuleGroup.GameMain.ModuleName);
            });

            btn_quit.AddClickListener(() => {
                NsnLog.Print("���� ----- ����˳���ť");
            });

            btn_option.AddClickListener(() => {
                NsnLog.Print("���� ----- ������ð�ť");
            });
        }
        
        protected override void OnStart()
        {
            base.OnStart();
        }
    }
}
