//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever.Core.HUD;
    using NeverSayNever.Utilities;

    public partial class GameMainPanel : NeverSayNever.Core.HUD.UIBasePanel
    {
        
        protected override void OnAwake()
        {
            base.OnAwake();
            ULog.Print("初始化GamemainPanel");

            

            btn_start.AddClickListener(()=>{
                ULog.Print("测试 ----- 点击开始按钮");

                GameSceneManager.LoadSceneAsync("example_scene");
                NeverSayNever.Core.UIManager.Instance.ClosePanel(UIModuleDefine.GameMain);
            });

            btn_quit.AddClickListener(() => {
                ULog.Print("测试 ----- 点击退出按钮");
            });

            btn_option.AddClickListener(() => {
                ULog.Print("测试 ----- 点击设置按钮");
            });
        }
        
        protected override void OnStart()
        {
            base.OnStart();
        }
    }
}
