//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever;

    public partial class GameMainPanel : NeverSayNever.UIBasePanel
    {

        protected override void OnAwake()
        {
            base.OnAwake();
            btn_start.AddClickListener(
                () =>{ PrintClickedBtnName(btn_start.gameObject);
                    SceneMgr.LoadSceneAsync("example_scene");
                });
            btn_quit.AddClickListener(
                () => { PrintClickedBtnName(btn_start.gameObject); });
            btn_option.AddClickListener(
                () => { PrintClickedBtnName(btn_start.gameObject); });
        }
        private void PrintClickedBtnName(GameObject go)
        {
            NsnLog.Print($"On {go.name} clicked");
        }
    }
}
