//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

using NeverSayNever;

public partial class CommonItem : UIBasePanel
{
    
    private Image img_bg;
    
    private Image img_icon;
    
    private TextMeshProUGUI tmp_value;
    
    protected override void OnInitAttribute()
    {
        this.img_bg = Info.Collection["Img_Bg"] as UnityEngine.UI.Image;
        this.img_icon = Info.Collection["Img_Icon"] as UnityEngine.UI.Image;
        this.tmp_value = Info.Collection["Tmp_Value"] as TMPro.TextMeshProUGUI;
    }
}
