//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverSayNever.Example
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;
    using NeverSayNever.Core.HUD;
    
    
    public partial class GameLoadingPanel : NeverSayNever.Core.HUD.UIBasePanel
    {
        
        private TextMeshProUGUI tmp_tip;
        
        private Slider slider_progress;
        
        private TextMeshProUGUI tmp_progress;
        
        protected override void OnInitAttribute()
        {
            base.OnInitAttribute();
            this.tmp_tip = Info.Collection["tmp_tip"] as TMPro.TextMeshProUGUI;
            this.slider_progress = Info.Collection["slider_progress"] as UnityEngine.UI.Slider;
            this.tmp_progress = Info.Collection["tmp_progress"] as TMPro.TextMeshProUGUI;
        }
    }
}
